/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseAmountTextField: typeof import('./src/view/widget/Base/BaseAmountTextField.vue')['default']
    BaseAutoComplete: typeof import('./src/view/widget/Base/BaseAutoComplete.vue')['default']
    BaseButton: typeof import('./src/view/widget/Base/BaseButton.vue')['default']
    BaseButtonGroup: typeof import('./src/view/widget/Base/BaseButtonGroup.vue')['default']
    BaseCardLayout: typeof import('./src/view/widget/Base/BaseCardLayout.vue')['default']
    BaseCheckbox: typeof import('./src/view/widget/Base/BaseCheckbox.vue')['default']
    BaseComboBox: typeof import('./src/view/widget/Base/BaseComboBox.vue')['default']
    BaseDateTimeTextField: typeof import('./src/view/widget/Base/BaseDateTimeTextField.vue')['default']
    BaseEditor: typeof import('./src/view/widget/Base/BaseEditor.vue')['default']
    BaseFileInput: typeof import('./src/view/widget/Base/BaseFileInput.vue')['default']
    BaseFilePicker: typeof import('./src/view/widget/Base/BaseFilePicker.vue')['default']
    BaseForm: typeof import('./src/view/widget/Base/BaseForm.vue')['default']
    BaseIconButton: typeof import('./src/view/widget/Base/BaseIconButton.vue')['default']
    BaseKeyValueSimpleTable: typeof import('./src/view/widget/Base/BaseKeyValueSimpleTable.vue')['default']
    BaseModal: typeof import('./src/view/widget/Base/BaseModal.vue')['default']
    BaseNumberPicker: typeof import('./src/view/widget/Base/BaseNumberPicker.vue')['default']
    BaseRangeDatePickerInputTextField: typeof import('./src/view/widget/Base/BaseRangeDatePickerInputTextField.vue')['default']
    BaseSelect: typeof import('./src/view/widget/Base/BaseSelect.vue')['default']
    BaseSqaureButton: typeof import('./src/view/widget/Base/BaseSqaureButton.vue')['default']
    BaseStepper: typeof import('./src/view/widget/Base/BaseStepper.vue')['default']
    BaseStepperLayout: typeof import('./src/view/widget/Base/BaseStepperLayout.vue')['default']
    BaseTabLayout: typeof import('./src/view/widget/Base/BaseTabLayout.vue')['default']
    BaseTable: typeof import('./src/view/widget/Base/BaseTable.vue')['default']
    BaseTextArea: typeof import('./src/view/widget/Base/BaseTextArea.vue')['default']
    BaseTextField: typeof import('./src/view/widget/Base/BaseTextField.vue')['default']
    BaseTimePickerTextField: typeof import('./src/view/widget/Base/BaseTimePickerTextField.vue')['default']
    BaseTimeTextField: typeof import('./src/view/widget/Base/BaseTimeTextField.vue')['default']
    BaseToggleButton: typeof import('./src/view/widget/Base/BaseToggleButton.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    DatePickerInputTextField: typeof import('./src/view/widget/Base/DatePickerInputTextField.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
  }
}
